---
language: python
sudo: required
before_install:
  - sudo pip install ansible urllib3 pyOpenSSL ndg-httpsclient pyasn1
  - gem install bundle
  - bundle install

script:
  - (cd ./test; ansible-playbook -i localhost, ./integration/default/site.yml -c local)
  - bundle exec inspec exec test/integration/default/inspec/docker.rb
